### ISSUE TITLE
code bugs 

### ISSUE THREAD

**Issue by lsmiao1209** [aodongli/zero-shot-ad-via-batch-norm#1]
I encountered an issue while running the AnoShift dataset with your zeroshot_trainer.py script. Every time the code reaches line 63 in zeroshot_trainer.py, I get the following error:

File "/luyi/zeroshot/anoshift/trainers/zeroshot_trainer.py", line 63, in detect_outliers
    x_qry, y_qry = loader.next(mode=mode)
ValueError: too many values to unpack (expected 2)

Could you clarify what format loader.next(mode=mode) should return? Is it supposed to return exactly two values (e.g., x_qry and y_qry)?Any suggestions on how to fix or further debug this issue?

**Comment by aodongli** [comment]
Great to know you solved this! 

Sorry there are some inconsistencies in the code (see the inconsistent number of returns [here](https://github.com/aodongli/zero-shot-ad-via-batch-norm/blob/54f1a6026cda4a501d870e49b7d49004b38a16fe/anoshift-cifar100c-omniglot/data_loader/anoshift.py#L232C32-L232C37)). Please remove the `years` in the return values and let me know if there are any further errors. Thanks for noting this bug!
